export {default as Navbar} from './Navbar'
export {default as Hero} from './Hero'
export {default as Categories} from './Categories'
export {default as Products} from './Products'
export {default as TopProducts} from './TopProducts'
export {default as Footer} from './Footer'
export {default as ProductsDetail} from './ProductDetail'